# Generated by Django 4.2.16 on 2024-12-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="expense", name="category",),
        migrations.RemoveField(model_name="expense", name="paid_by",),
        migrations.RemoveField(model_name="expense", name="user",),
        migrations.DeleteModel(name="Budget",),
        migrations.DeleteModel(name="Category",),
        migrations.DeleteModel(name="Expense",),
        migrations.DeleteModel(name="User",),
    ]
