# Generated by Django 4.2.16 on 2024-12-09 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0005_remove_budget_user_remove_expense_user_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account", name="email", field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
