# Generated by Django 4.2.16 on 2024-12-10 06:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_category_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="total_expenses",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=10
            ),
        ),
    ]
