# Generated by Django 4.2.16 on 2024-12-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_budget_total_expenses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category", name="name", field=models.CharField(max_length=150),
        ),
    ]
